### ISSUE TITLE
Case hentaipdf

### ISSUE THREAD

**Issue by ozandesu** [LoL-Human/Case-WA-Bot#1]
TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined
Error bang, tolong di perbaiki
 (udah work)

**Comment by LoL-Human** [comment]
> TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined
> Error bang, tolong di perbaiki

ok
